### ISSUE TITLE
Algorithm doesn't find closest _indexed_ color

### ISSUE THREAD

**Issue by trapd00r** [perlancar/perl-Color-ANSI-Util#2]
https://github.com/perlancar/perl-Color-ANSI-Util/blob/934ee436510fcd65412c530d86cb2f18fcfab96f/lib/Color/ANSI/Util.pm#L186

From pod:
"Algorithm for finding closest indexed color from RGB color"

As far as I can tell this is false; you never actually read the indexed color but instead have a hard coded table of xterm defaults. Please correct me if I'm wrong.

[here's how it can be done](https://github.com/trapd00r/Term-ExtendedColor-Xresources/blob/master/lib/Term/ExtendedColor/Xresources.pm#L26)

**Comment by perlancar** [comment]
Sorry for the very late response. I didn't see the notification for this issue.

I've implemented this in commit 490f8f6.
